### ISSUE TITLE
关于  19.特效快速预览 造成 SceneView 无法拖拽的Bug

### ISSUE THREAD

**Issue by maxwell9421** [XINCGer/UnityToolchainsTrick#30]
19.特效快速预览
![image](https://user-images.githubusercontent.com/13503439/127482101-28e7ee48-e9f8-4192-a5f5-2330970190d5.png)
这边做了处理（ParticleSystemGameObjectEditor 160 行），但是在 Unity 2020.3.10f1 版本中，依然是不能拖拽到SceneView.
报错信息如下
![image](https://user-images.githubusercontent.com/13503439/127480842-b36c79c4-ceda-4255-a6ed-e5eeb9dcf0c2.png)

ArgumentException: method argument length mismatch
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEditor.EditorWrapper.Init (UnityEngine.Object obj, UnityEditor.EditorFeatures requirements) (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.EditorWrapper.Make (UnityEngine.Object obj, UnityEditor.EditorFeatures requirements) (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.EditorCache.get_Item (UnityEngine.Object o) (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.SceneView.CallEditorDragFunctions (System.Collections.Generic.IList`1[T] dragAndDropObjects) (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.SceneView.HandleDragging () (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.SceneView.OnGUI () (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)
UnityEditor.DockArea.OldOnGUI () (at <c77ced6644e541b7ad3d7315a5e92a0a>:0)

希望可以寻求一些帮助，感谢。

**Comment by Kaorixsol** [comment]
好，这边查一下

**Comment by maxwell9421** [comment]
这个Issue, 我查了下Unity的源码，发现报错的关键原因是由于2020.2.0 版本的一次更新中，OnSceneDrag的回调函数参数由
![U_ZGJ$ A)P@M@8FDB1)SR%1](https://user-images.githubusercontent.com/13503439/127521648-8ae0c364-bcda-4e01-84a1-1a87011cab18.png)

 变成了 
![W1S($WVSI36 V@5O1V}C8GN](https://user-images.githubusercontent.com/13503439/127521659-2290a17b-a168-48f9-aae9-76317d8ad0f4.png)

日志
![image](https://user-images.githubusercontent.com/13503439/127521710-70971b55-2b1b-4658-be35-ee429e7757d8.png)
